# Generated by Django 6.0.2 on 2026-02-14 07:10

import scholarships.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('app_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('passport', models.FileField(blank=True, null=True, upload_to=scholarships.models.get_upload_path)),
                ('photo', models.FileField(blank=True, null=True, upload_to=scholarships.models.get_upload_path)),
                ('graduation_certificate', models.FileField(blank=True, null=True, upload_to=scholarships.models.get_upload_path)),
                ('criminal_record', models.FileField(blank=True, null=True, upload_to=scholarships.models.get_upload_path)),
                ('medical_examination', models.FileField(blank=True, null=True, upload_to=scholarships.models.get_upload_path)),
                ('letter_of_recommendation_1', models.FileField(blank=True, null=True, upload_to=scholarships.models.get_upload_path)),
                ('letter_of_recommendation_2', models.FileField(blank=True, null=True, upload_to=scholarships.models.get_upload_path)),
                ('study_plan', models.FileField(blank=True, null=True, upload_to=scholarships.models.get_upload_path)),
                ('english_certificate', models.FileField(blank=True, null=True, upload_to=scholarships.models.get_upload_path)),
            ],
            options={
                'db_table': 'applications',
            },
        ),
        migrations.CreateModel(
            name='scholarships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('degree', models.CharField(choices=[('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'PhD')], max_length=50)),
                ('language', models.CharField(max_length=100)),
                ('scholarship_type', models.CharField(choices=[('full', 'Full Scholarship'), ('partial', 'Partial Scholarship'), ('merit', 'Merit Based')], max_length=50)),
                ('deadline', models.DateField()),
                ('semester', models.CharField(choices=[('fall', 'Fall'), ('spring', 'Spring'), ('summer', 'Summer')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eligibility', models.TextField()),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
