# Generated by Django 6.0.2 on 2026-02-16 06:26

import django.db.models.deletion
import scholarships.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scholarships',
            options={'verbose_name_plural': 'scholarships'},
        ),
        migrations.AddField(
            model_name='application',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='assigned_hq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hq_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for HQ to complete university application', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarships',
            name='agent_commission',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount (USD) the Main Agent earns per completed application', max_digits=10),
        ),
        migrations.AddField(
            model_name='scholarships',
            name='hq_commission',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount (USD) HQ earns per completed application', max_digits=10),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('documents_verified', 'Documents Verified'), ('payment_verified', 'Payment Verified'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('admission_letter_uploaded', 'Admission Letter Uploaded'), ('admission_letter_approved', 'Admission Letter Approved'), ('jw02_uploaded', 'JW02 Uploaded'), ('jw02_approved', 'JW02 Approved'), ('letter_pending', 'Letter Pending Revision'), ('complete', 'Complete')], default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AdmissionLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=scholarships.models.get_admission_letter_path)),
                ('status', models.CharField(choices=[('pending_verification', 'Pending Verification'), ('approved', 'Approved'), ('revision_requested', 'Revision Requested')], default='pending_verification', max_length=30)),
                ('revision_note', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_letters', to='scholarships.application')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_admission_letters', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_admission_letters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admission_letters',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=30, null=True)),
                ('new_status', models.CharField(max_length=30)),
                ('note', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='scholarships.application')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Application status histories',
                'db_table': 'application_status_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='JW02Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=scholarships.models.get_jw02_path)),
                ('status', models.CharField(choices=[('pending_verification', 'Pending Verification'), ('approved', 'Approved')], default='pending_verification', max_length=30)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jw02_forms', to='scholarships.application')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_jw02_forms', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_jw02_forms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jw02_forms',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
