# Generated by Django 6.0.2 on 2026-02-16 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0003_alter_scholarships_options_application_approved_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipCommission',
            fields=[
            ],
            options={
                'verbose_name': 'Scholarship Commission',
                'verbose_name_plural': 'Scholarship Commissions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('scholarships.scholarships',),
        ),
    ]
