# Generated by Django 6.0.2 on 2026-02-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0004_scholarshipcommission'),
    ]

    operations = [
        migrations.AddField(
            model_name='jw02form',
            name='revision_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('documents_verified', 'Documents Verified'), ('payment_verified', 'Payment Verified'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('admission_letter_uploaded', 'Admission Letter Uploaded'), ('admission_letter_approved', 'Admission Letter Approved'), ('jw02_uploaded', 'JW02 Uploaded'), ('jw02_approved', 'JW02 Approved'), ('letter_pending', 'Letter Pending Revision'), ('jw02_pending', 'JW02 Pending Revision'), ('complete', 'Complete')], default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='jw02form',
            name='status',
            field=models.CharField(choices=[('pending_verification', 'Pending Verification'), ('approved', 'Approved'), ('revision_requested', 'Revision Requested')], default='pending_verification', max_length=30),
        ),
    ]
