# Generated by Django 6.0.2 on 2026-02-24 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
        ('scholarships', '0005_jw02form_revision_note_alter_application_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='office',
            field=models.ForeignKey(blank=True, help_text='Branch office that owns/created this application.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='office.office'),
        ),
    ]
