# Generated by Django 6.0.2 on 2026-03-06 12:04

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    """Generate slugs for existing scholarships."""
    Scholarship = apps.get_model('scholarships', 'scholarships')
    used_slugs = set()
    for s in Scholarship.objects.all():
        base_slug = slugify(s.name) or f'scholarship-{s.pk}'
        slug = base_slug
        counter = 2
        while slug in used_slugs:
            slug = f'{base_slug}-{counter}'
            counter += 1
        used_slugs.add(slug)
        s.slug = slug
        s.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0006_application_office'),
    ]

    operations = [
        # Step 1: Add slug field (nullable, not unique yet)
        migrations.AddField(
            model_name='scholarships',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        # Step 2: Populate slugs for existing rows
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
        # Step 3: Make slug unique
        migrations.AlterField(
            model_name='scholarships',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly name (auto-generated from name).', max_length=200, unique=True),
        ),
    ]
