# Generated by Django 6.0.2 on 2026-02-24 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
        ('users', '0002_alter_user_role_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='office',
            field=models.ForeignKey(blank=True, help_text='Branch office this user belongs to (for office workers and agents).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='office.office'),
        ),
    ]
