# Generated by Django 6.0.2 on 2026-02-14 07:10

import finance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='application_payment',
            fields=[
                ('application_payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt_pdf', models.FileField(upload_to=finance.models.get_receipt_upload_path)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('under_review', 'Under Review'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'application_payments',
            },
        ),
        migrations.CreateModel(
            name='bank_account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('account_holder_name', models.CharField(max_length=255)),
                ('iban', models.CharField(blank=True, max_length=50, null=True)),
                ('swift_code', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bank_accounts',
            },
        ),
    ]
