# Generated by Django 6.0.2 on 2026-02-14 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('scholarships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application_payment',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='scholarships.application'),
        ),
    ]
