# Generated by Django 6.0.2 on 2026-02-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Yaamaan Education Consultants', help_text='Displayed in the navbar, browser tab title, and footer.', max_length=200)),
                ('tagline', models.CharField(blank=True, default='Your Gateway to International Education', help_text='Short tagline shown on the home page hero section.', max_length=300)),
                ('logo', models.ImageField(blank=True, help_text='Site logo (recommended: PNG with transparent background, 200×60px).', null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, help_text='Browser tab favicon (recommended: 32×32px .ico or .png).', null=True, upload_to='site/')),
                ('meta_description', models.CharField(blank=True, default='Yaamaan Education Consultants - Helping students achieve their dreams of studying abroad.', help_text='Meta description for search engines (max 160 chars recommended).', max_length=300)),
                ('meta_keywords', models.CharField(blank=True, default='education, consultants, study abroad, scholarships, international students', help_text='Comma-separated keywords for SEO.', max_length=500)),
                ('og_image', models.ImageField(blank=True, help_text='Open Graph image for social media sharing (recommended: 1200×630px).', null=True, upload_to='site/')),
                ('contact_email', models.EmailField(blank=True, default='info@yaamaan.com', help_text='Public contact email displayed on the site.', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', help_text='Public contact phone number.', max_length=30)),
                ('address', models.TextField(blank=True, default='', help_text='Office address displayed in the footer / contact page.')),
                ('facebook_url', models.URLField(blank=True, default='')),
                ('instagram_url', models.URLField(blank=True, default='')),
                ('twitter_url', models.URLField(blank=True, default='')),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('youtube_url', models.URLField(blank=True, default='')),
                ('whatsapp_number', models.CharField(blank=True, default='', help_text='WhatsApp number with country code, e.g. +1234567890', max_length=30)),
                ('google_analytics_id', models.CharField(blank=True, default='', help_text='Google Analytics Measurement ID (e.g. G-XXXXXXXXXX).', max_length=30)),
                ('footer_text', models.CharField(blank=True, default='© 2024 Yaamaan Education Consultants. All rights reserved.', help_text='Custom footer copyright / text.', max_length=500)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
                'db_table': 'site_settings',
            },
        ),
    ]
