# Generated by Django 6.0.2 on 2026-02-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='body_bg_color',
            field=models.CharField(default='#ffffff', help_text='Page background color (hex). Default: #ffffff (white).', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='danger_color',
            field=models.CharField(default='#dc3545', help_text='Danger/error color (hex). Default: #dc3545 (Bootstrap red).', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_bg_color',
            field=models.CharField(default='#1a1a2e', help_text='Footer background color (hex). Default: #1a1a2e.', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_gradient_end',
            field=models.CharField(default='#1b2838', help_text='Hero section gradient end color (hex). Default: #1b2838.', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_gradient_start',
            field=models.CharField(default='#0d1b2a', help_text='Hero section gradient start color (hex). Default: #0d1b2a.', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='info_color',
            field=models.CharField(default='#0dcaf0', help_text='Info color (hex). Default: #0dcaf0 (Bootstrap cyan).', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='navbar_bg_color',
            field=models.CharField(default='#212529', help_text='Navbar / header background color (hex). Default: #212529 (dark).', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='primary_color',
            field=models.CharField(default='#0d6efd', help_text='Primary brand color (hex). Used for buttons, links, navbar. Default: #0d6efd (Bootstrap blue).', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='secondary_color',
            field=models.CharField(default='#6c757d', help_text='Secondary color (hex). Used for secondary buttons and badges. Default: #6c757d.', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='success_color',
            field=models.CharField(default='#198754', help_text='Success/positive color (hex). Default: #198754 (Bootstrap green).', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='warning_color',
            field=models.CharField(default='#ffc107', help_text='Warning color (hex). Default: #ffc107 (Bootstrap yellow).', max_length=7),
        ),
    ]
