# Generated by Django 6.0.2 on 2026-02-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_sitesettings_body_bg_color_sitesettings_danger_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='body_bg_color',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='danger_color',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_bg_color',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_gradient_end',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_gradient_start',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='info_color',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='navbar_bg_color',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='secondary_color',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='success_color',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='warning_color',
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(blank=True, default='info@dfseducation.com', help_text='Public contact email displayed on the site.', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_text',
            field=models.CharField(blank=True, default='© 2026 DFS Education. All rights reserved.', help_text='Custom footer copyright / text.', max_length=500),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_description',
            field=models.CharField(blank=True, default='DFS Education - Expert consultancy for students seeking international scholarships and university admissions.', help_text='Meta description for search engines (max 160 chars recommended).', max_length=300),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='DFS Education', help_text='Displayed in the navbar, browser tab title, and footer.', max_length=200),
        ),
    ]
