# Generated by Django 6.0.2 on 2026-02-24 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name, e.g. "Istanbul Office"', max_length=200)),
                ('code', models.SlugField(help_text='Short unique code, e.g. "istanbul", "cairo"', max_length=30, unique=True)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('is_default', models.BooleanField(default=False, help_text='Mark as the default/fallback office for unmatched regions.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'offices',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OfficeRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(help_text='ISO 3166-1 alpha-2 country code, e.g. "TR", "EG"', max_length=3)),
                ('country_name', models.CharField(help_text='Human-readable country name, e.g. "Turkey", "Egypt"', max_length=100)),
                ('city', models.CharField(blank=True, default='', help_text='Optional city for more specific routing (leave blank for whole country).', max_length=100)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='office.office')),
            ],
            options={
                'db_table': 'office_regions',
                'ordering': ['country_name', 'city'],
                'unique_together': {('country_code', 'city')},
            },
        ),
    ]
