# Generated by Django 6.0.2 on 2026-02-24 02:32

from django.db import migrations


def create_default_office(apps, schema_editor):
    """Create a default 'Main Office' and assign all existing staff/apps to it."""
    Office = apps.get_model('office', 'Office')
    User = apps.get_model('users', 'User')
    Application = apps.get_model('scholarships', 'Application')

    office, _ = Office.objects.get_or_create(
        code='main',
        defaults={
            'name': 'Main Office',
            'is_default': True,
            'is_active': True,
        },
    )

    # Assign all office-role and agent-role users to the default office
    User.objects.filter(role__in=['office', 'agent'], office__isnull=True).update(office=office)
    # Assign all students with no office to the default office
    User.objects.filter(role='user', office__isnull=True).update(office=office)
    # Assign all applications with no office to the default office
    Application.objects.filter(office__isnull=True).update(office=office)


def reverse_default_office(apps, schema_editor):
    """Remove office assignments (reverse migration)."""
    User = apps.get_model('users', 'User')
    Application = apps.get_model('scholarships', 'Application')
    Office = apps.get_model('office', 'Office')

    User.objects.filter(office__isnull=False).update(office=None)
    Application.objects.filter(office__isnull=False).update(office=None)
    Office.objects.filter(code='main').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
        ('users', '0003_user_city_user_country_user_office'),
        ('scholarships', '0006_application_office'),
    ]

    operations = [
        migrations.RunPython(create_default_office, reverse_default_office),
    ]
